version: '3.8'

services:
  # Servidor de Base de Datos (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: erp_sap_lite_db
    restart: always
    environment:
      POSTGRES_USER: sap_user
      POSTGRES_PASSWORD: sap_password123
      POSTGRES_DB: sap_lite_db
    ports:
      - "5432:5432"
    volumes:
      # Copia el archivo SQL a la carpeta interna de Postgres para que cree las tablas al iniciar
      - ./database/schema_init.sql:/docker-entrypoint-initdb.d/schema_init.sql
      # Mantiene los datos guardados en tu compu aunque apagues el contenedor
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: